# Generated by Django 4.0.5 on 2022-06-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_whatsapp_alertstatus_whatsapp_lastmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp',
            name='alertStatus',
            field=models.CharField(default='ON', max_length=15),
        ),
    ]
