# Generated by Django 4.0.5 on 2022-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_alter_whatsapp_alertstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsapp',
            options={'verbose_name': 'Whatsapp User', 'verbose_name_plural': 'Whatsapp User'},
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='alertStatus',
            field=models.CharField(default='ON', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='lastmessage',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
