# Generated by Django 4.0.4 on 2022-06-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('chat_id', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('temperature1', models.CharField(max_length=15)),
                ('humidity1', models.CharField(max_length=15)),
                ('temperature2', models.CharField(max_length=15)),
                ('humidity2', models.CharField(max_length=15)),
                ('wind', models.CharField(max_length=15)),
                ('gas', models.CharField(max_length=15)),
                ('alarm', models.CharField(max_length=15)),
                ('voltage', models.CharField(max_length=15)),
                ('alarmStatus', models.CharField(max_length=10)),
                ('machineStatus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('imei', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('clients', models.ManyToManyField(blank=True, to='MessageStore.client')),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature1', models.CharField(max_length=5)),
                ('humidity1', models.CharField(max_length=5)),
                ('temperature2', models.CharField(max_length=5)),
                ('humidity2', models.CharField(max_length=5)),
                ('wind', models.CharField(max_length=5)),
                ('gas', models.CharField(max_length=5)),
                ('alarm', models.CharField(max_length=5)),
                ('voltage', models.CharField(max_length=5)),
                ('alarmStatus', models.CharField(default='off', max_length=10)),
                ('machineStatus', models.CharField(default='not working', max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessageStore.device')),
            ],
            options={
                'verbose_name_plural': 'Datas',
            },
        ),
    ]
