# Generated by Django 4.0.4 on 2022-06-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0002_alter_client_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='alarmStatus',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='language',
            name='machineStatus',
            field=models.CharField(max_length=15),
        ),
    ]
