# Generated by Django 4.0.4 on 2022-06-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0003_alter_language_alarmstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='gasWarning',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='inverWarning',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='tempWarning',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='volWarning',
            field=models.CharField(default='', max_length=30),
        ),
    ]
