# Generated by Django 4.0.5 on 2022-06-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_alter_whatsapp_options_alter_whatsapp_alertstatus_and_more'),
        ('MessageStore', '0011_alter_client_options_language_chooselanguage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegroup',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='SMAV from 0 to 10'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='whatsapps',
            field=models.ManyToManyField(blank=True, to='webhooks.whatsapp', verbose_name='WhatsApp User'),
        ),
        migrations.AddField(
            model_name='language',
            name='smavGroup',
            field=models.CharField(default='SMAV Group', max_length=30),
        ),
    ]
