# Generated by Django 4.0.5 on 2022-06-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0012_devicegroup_description_devicegroup_whatsapps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicegroup',
            options={'verbose_name_plural': 'Device Group'},
        ),
        migrations.AddField(
            model_name='language',
            name='gasState',
            field=models.CharField(default='Gas', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='generalState',
            field=models.CharField(default='General State', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='machineState',
            field=models.CharField(default='Machine State', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='temperatureState',
            field=models.CharField(default='Temperature', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='windState',
            field=models.CharField(default='Wind', max_length=30),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
