# Generated by Django 4.0.5 on 2022-06-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0013_alter_devicegroup_options_language_gasstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
