# Generated by Django 4.0.5 on 2022-06-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0018_alter_data_machinestatus_alter_data_voltage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='voltageBattery',
        ),
        migrations.RemoveField(
            model_name='language',
            name='voltageBattery',
        ),
    ]
