# Generated by Django 4.0.5 on 2022-06-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0019_remove_data_voltagebattery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='battery',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='battery',
            field=models.CharField(default='Battery', max_length=15),
        ),
    ]
