# Generated by Django 4.0.5 on 2022-06-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0020_data_battery_language_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='battery',
            field=models.CharField(default='Battery Internal', max_length=15),
        ),
    ]
