# Generated by Django 4.0.5 on 2022-09-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0022_remove_data_battery_remove_language_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='gas',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='humidity1',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='humidity2',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature1',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature2',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='wind',
            field=models.FloatField(max_length=5),
        ),
    ]
