# Generated by Django 4.0.5 on 2022-09-18 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0024_device_latitude_device_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='device',
            name='maintainer',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='timeActive',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='timeMaintain',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 1, 32, 38, 332698)),
        ),
        migrations.AddField(
            model_name='device',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 1, 32, 38, 332711), editable=False),
        ),
    ]
