# Generated by Django 4.0.5 on 2022-09-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0028_language_maintainermenu_language_timeactivemenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='locationMenu',
            field=models.CharField(default='Location', max_length=30),
        ),
    ]
