# Generated by Django 4.0.5 on 2022-09-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0033_remove_device_timeactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='timeActive',
            field=models.CharField(default='0', editable=False, max_length=20),
        ),
    ]
