# Generated by Django 4.0.5 on 2022-09-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0035_language_smavsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='informationMenu',
            field=models.CharField(default='Device Information', max_length=24),
        ),
        migrations.AddField(
            model_name='language',
            name='modeMenu',
            field=models.CharField(default='Mode', max_length=24),
        ),
        migrations.AddField(
            model_name='language',
            name='signalDeviceMenu',
            field=models.CharField(default='Signal Quality', max_length=24),
        ),
        migrations.AddField(
            model_name='language',
            name='volSolarMenu',
            field=models.CharField(default='Voltage Solar', max_length=24),
        ),
    ]
