# Generated by Django 4.0.5 on 2022-10-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0042_data_temperatureh1_data_temperatureh2_device_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='acceptableSignal',
            field=models.CharField(default='Acceptable Signal', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='automatic',
            field=models.CharField(default='Automatic', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='excellentSignal',
            field=models.CharField(default='Excellent Signal', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='goodSignal',
            field=models.CharField(default='Good Signal', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='manual',
            field=models.CharField(default='Manual', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='nowDevice',
            field=models.CharField(default='Now device', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='offline',
            field=models.CharField(default='Offline', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='online',
            field=models.CharField(default='Online', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='weakSignal',
            field=models.CharField(default='Weak signal', max_length=30),
        ),
    ]
