# Generated by Django 4.0.4 on 2022-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(default='english', max_length=15),
        ),
    ]
