# Generated by Django 4.0.4 on 2022-06-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0004_language_gaswarning_language_inverwarning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='device',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='get_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='language',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
