# Generated by Django 4.0.5 on 2022-06-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
        ('MessageStore', '0006_remove_language_device_remove_language_get_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='whatsapps',
            field=models.ManyToManyField(blank=True, to='webhooks.whatsapp'),
        ),
    ]
