# Generated by Django 4.0.5 on 2022-06-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0008_remove_data_alarm_remove_data_alarmstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='alertStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='machineVoltage',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='temperatureAlert',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='data',
            name='machineStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='voltage',
            field=models.IntegerField(default=0),
        ),
    ]
