# Generated by Django 4.0.5 on 2022-06-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0016_devicegroup_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='voltageBattery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='voltageBattery',
            field=models.CharField(default='Voltage Battery', max_length=15),
        ),
    ]
