# Generated by Django 4.0.5 on 2022-09-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0023_alter_data_gas_alter_data_humidity1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.CharField(default='', max_length=20),
        ),
    ]
