# Generated by Django 4.0.5 on 2022-09-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0027_language_maintainer_language_timeactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='maintainerMenu',
            field=models.CharField(default='Maintainer', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='timeActiveMenu',
            field=models.CharField(default='Time Active', max_length=30),
        ),
    ]
