# Generated by Django 4.0.5 on 2022-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0029_language_locationmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='locationMenu',
            field=models.CharField(default='Location', max_length=24),
        ),
        migrations.AlterField(
            model_name='language',
            name='maintainer',
            field=models.CharField(default='Maintainer', max_length=24),
        ),
        migrations.AlterField(
            model_name='language',
            name='maintainerMenu',
            field=models.CharField(default='Maintainer', max_length=24),
        ),
        migrations.AlterField(
            model_name='language',
            name='timeActive',
            field=models.CharField(default='Time Active', max_length=24),
        ),
        migrations.AlterField(
            model_name='language',
            name='timeActiveMenu',
            field=models.CharField(default='Time Active', max_length=24),
        ),
    ]
