# Generated by Django 4.0.5 on 2022-09-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0030_alter_language_locationmenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='maintainer',
            field=models.CharField(default='Maintainer', max_length=30),
        ),
        migrations.AlterField(
            model_name='language',
            name='timeActive',
            field=models.CharField(default='Time Active', max_length=30),
        ),
    ]
