# Generated by Django 4.0.5 on 2022-09-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0032_alter_device_timeactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='timeActive',
        ),
    ]
