# Generated by Django 4.0.5 on 2022-09-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0036_language_informationmenu_language_modemenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='mode',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='signal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='volSolar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='mode',
            field=models.CharField(default='Mode', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='signalDevice',
            field=models.CharField(default='Signal Quality', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='volSolar',
            field=models.CharField(default='Voltage Solar', max_length=30),
        ),
    ]
