# Generated by Django 4.0.5 on 2022-10-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0038_data_volbat_language_volbat_language_volbatmenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='signal',
            field=models.CharField(default='', max_length=25),
        ),
    ]
