# Generated by Django 4.0.5 on 2022-10-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0039_alter_data_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='signal',
            field=models.FloatField(default=0),
        ),
    ]
