# Generated by Django 4.0.5 on 2022-10-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0041_remove_data_volsolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='temperatureH1',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='data',
            name='temperatureH2',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='language',
            name='temperatureH1',
            field=models.CharField(default='Temperature Humide 1', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='temperatureH2',
            field=models.CharField(default='Temperature Humide 2', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='timeActive',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
