# Generated by Django 4.0.5 on 2022-10-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_alter_whatsapp_options_alter_whatsapp_alertstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('language', models.CharField(default='English', max_length=15)),
                ('alertStatus', models.CharField(default='ON', editable=False, max_length=15)),
                ('temperatureAlert', models.IntegerField(default=1)),
                ('machineVoltage', models.IntegerField(default=12)),
                ('lastmessage', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'SMS User',
                'verbose_name_plural': 'SMS User',
            },
        ),
    ]
